[project]
name = "gotenberg-api"
version = "0.1.0"
description = "Library for generating site screenshots with Gotenberg"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
]
